package exception;

public class Arithemetic {

	public static void main(String[] args) {
		try {
			int a=30/0;

			}
			catch(Exception e)
			{
			System.out.println(e);
			}

	}

}
